ENUM_SCENES = {
    CONTROLLER_LOAD = 10,
    MAIN_MENU = 11,
    GAME = 12,
    TEST = 13
}

ENUM_DRAWORDER = {
    BACKGROUND = 1,
    MIDGROUND = 2,
    FOREGROUND = 3,
    SCENARIO = 4,
    CREATURES = 5
}
